# 适用于  nats-server-v2.14.1 版本

# [[instances]]
# server = "http://10.0.1.115:8222"
# labels = { instance="10.0.1.115"}
# response_timeout = "5s"
 
# [[instances]]
# address = "http://10.0.1.116:8222"
# labels = { instance="10.0.1.116"}
# response_timeout = "5s"

# [[instances]]
# address = "http://10.0.1.117:8222"
# labels = { instance="10.0.1.117"}
# response_timeout = "5s"

